# Exploring DREAM3 dataset

Third annual DREAM challenge (DREAM3) (2008), a gene expression
prediction challenge.

The original challenge was to predict a block 
of missing data. Here we use the same dataset 
for a different purpose: to discover a gene regulatory
network for yeast

yeast (saccharomyces cerevisiae) About 6,000 genes 

ecoli has 5,000 genes 
but is a prokaryote. yeast is an eukaryote, like plants, and humans

humans ~ 21,000 genes 

fruit flies (drosophila) ~ 14,000 genes

GAT1, GCN4 and LEU3 are TFs (Transcription Factors, i.e.,  proteins that latch onto a DNA segment)

4 yeast strains
1. wild type (wt) 
2. GAT1 deletion strain (gat1$\Delta$)
3. GCN4 deletion strain (gcn4$\Delta$) 
4. LEU3 deletion strain (leu3$\Delta$)

time course (8 times): 
T= 0, 10, 20, 30, 45, 60, 90 and 120 minutes

T: time since added 3-aminotriazole (3AT), which is an
inhibitor of an enzyme in the histidine biosynthesis pathway.
No 3AT at T=0

data: expression levels for these 4 different strains of yeast, with missing data

missing data: for gat1$\Delta1$ strain, block of data of shape 50 by 8 (50 genes and 8 times).

The dataset contains 9,335 rows even though yeast have ~ 6,000 genes. The reason for 
9,335 is explained in misc/Affymetric-microarray.md

The dataset contains 35 columns: (4 strains) X (8 times) + 3 = 35

The 3 extra columns are:
1. probeID
2. geneName
3. L0,  expression level (arbitrary units) for probeID of parental strain at t=0

The other columns are log_2(L/L0) where L is the expression level 

slots for missing data have been filled with "PREDICT" string


Refs.
-----

https://dreamchallenges.org/dream-3-gene-expression-prediction/

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0008944

https://github.com/s-nakhawa/DREAM3-Gene-Expression-Prediction-Challenge

https://en.wikipedia.org/wiki/DREAM_Challenges

In [1]:
# this makes sure it starts looking for things from the project folder down.
import os
import sys
os.chdir('../')
sys.path.insert(0,os.getcwd())
print(os.getcwd())

C:\Users\rrtuc\Desktop\backed-up\python-projects\gene_causal_mapper

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data/DREAM3_GeneExpressionChallenge_ExpressionData_UPDATED.txt', sep='\t')
print(df.shape)
df.head(15)

(9335, 35)

,ProbeID,geneName,"absolute expression, parental strain t=0 (arbitrary units)",wt t=0,wt t=10,wt t=20,wt t=30,wt t=45,wt t=60,wt t=90,...,gcn4-deletion t=90,gcn4-deletion t=120,leu3-deletion t=0,leu3-deletion t=10,leu3-deletion t=20,leu3-deletion t=30,leu3-deletion t=45,leu3-deletion t=60,leu3-deletion t=90,leu3-deletion t=120
0,10000_at,NaN,0.194,0,0.080088,-0.021480,-0.207893,0.070967,-0.066261,-0.063503,...,0.081614,-0.079975,-0.185232,-0.205393,-0.071763,-0.060739,0.000000,0.042457,-0.146655,-0.246104
1,10001_at,MID2,1.480,0,-0.466758,-0.376290,-0.619178,-0.199123,-0.107018,-0.142740,...,0.302226,-0.147958,-0.149259,-0.382944,0.182786,-0.007196,0.020340,-0.052416,0.074001,0.187707
2,10002_i_at,NaN,13.960,0,-0.312665,-0.146655,-0.640621,-0.097611,-0.200379,-0.304511,...,-0.478195,-0.610700,-0.385155,-0.590722,-0.319618,-0.109695,-0.468844,-0.442545,-0.284514,-0.356144
3,10003_f_at,RPS25B,132.600,0,-0.182692,-0.105678,-0.447844,-0.119024,-0.167358,-0.244887,...,-0.302173,-0.473008,-0.284514,-0.492622,-0.358396,-0.404903,-0.499782,-0.343692,-0.263034,-0.376290
4,10004_at,NaN,0.148,0,0.164884,0.182786,0.186065,0.103147,0.129734,0.107803,...,0.112475,0.349235,0.036526,0.013043,-0.005759,0.057392,0.052895,0.163268,-0.024320,-0.064883
5,10005_at,NUP2,3.830,0,-0.238787,-0.140124,-0.804880,-0.153157,-0.164786,-0.358396,...,-0.128293,-0.599318,0.005782,-0.059355,0.239566,-0.062122,0.054392,-0.150560,0.128156,0.101598
6,10006_at,SGD1,1.125,0,0.543720,-0.178874,-0.718964,-0.052416,-0.209141,-0.178874,...,-0.303342,-0.321928,-0.439357,-0.246104,-0.147958,-0.112367,-0.241230,-0.242450,-0.197865,-0.331132
7,10007_at,VRP1,2.045,0,0.011588,-0.132248,-0.120352,-0.166073,-0.257011,-0.442545,...,-0.473008,-0.590722,-0.316146,0.078564,0.220950,-0.543991,0.018878,-0.489543,-0.266637,-0.097611
8,10008_at,NaN,0.346,0,0.163268,0.205896,0.537424,0.186065,0.177882,0.080088,...,0.058894,0.246395,-0.142740,-0.166073,-0.097611,-0.008630,0.036526,0.030619,-0.160920,-0.053806
9,10009_at,NaN,0.926,0,0.438307,0.160040,0.272297,0.352916,0.312939,-0.191563,...,-0.018634,-0.230203,0.189351,-0.078610,-0.073135,-0.073135,-0.053806,0.305788,0.110916,-0.052416
10,10010_at,ATP14,7.689,0,-0.364012,-0.834307,-1.027154,-0.292782,-0.253384,-0.360645,...,0.067939,-0.313826,-0.172488,-0.411426,-0.490570,-0.401630,-0.421156,-0.253384,-0.448901,-0.480265
11,10011_at,NaN,0.162,0,0.182786,0.103147,0.172994,0.120294,0.100051,0.067939,...,-0.012926,-0.002883,0.045431,0.018878,0.140826,-0.028569,-0.010064,-0.024320,0.030619,-0.186501
12,10012_at,NaN,0.859,0,-1.480782,-1.623399,-1.740712,-1.308011,-1.276199,-0.912267,...,-0.529071,-0.681674,0.962969,-0.741575,-0.397255,-0.273814,-0.014355,0.325539,-0.097611,-0.236340
13,10013_at,YHC1,1.015,0,0.187707,-0.124328,-0.606916,-0.182692,-0.149259,-0.192825,...,0.038006,-0.008630,-0.001442,0.107803,-0.237564,0.090803,-0.176323,-0.005759,0.080088,0.186065
14,10014_at,ECM38,2.889,0,-0.723340,-0.523060,-0.387363,-0.361768,-0.668119,-0.737254,...,-0.325386,-0.804054,0.526992,-0.140124,0.058894,-0.457332,-0.067639,-0.489543,-0.273814,-0.220330

In [4]:
df = pd.read_csv('data/DREAM3GoldStandard_ExpressionChallenge.txt', sep='\t')
print(df.shape)
df.head(15)

(50, 10)

,probeID,gene_name,rank_time0,rank_time10,rank_time20,rank_time30,rank_time45,rank_time60,rank_time90,rank_time120
0,5646_at,ALD5,32,24,40,33,32,32,38,34
1,8593_at,ARG1,9,19,16,27,46,44,26,28
2,11114_at,ARG3,3,10,26,42,47,41,22,33
3,4537_at,ARG4,19,17,22,40,44,46,31,35
4,4568_at,ARN1,20,27,24,14,12,11,10,16
5,7291_at,BAP2,37,28,36,25,31,26,37,30
6,4321_at,BAT1,26,29,28,21,17,25,29,26
7,4899_at,CLB6,40,47,48,48,48,19,23,18
8,3190_f_at,COS8,46,46,47,44,43,38,44,44
9,10105_at,CRR1,47,43,43,46,23,22,9,6
10,9442_s_at,DDR48,2,5,4,4,4,6,5,11
11,4392_at,DSE2,17,33,19,16,7,8,25,5
12,10899_at,ECM27,10,32,2,3,1,2,2,3
13,9592_at,ECM40,7,9,11,37,41,40,18,38
14,10521_at,FMP46,28,35,32,23,13,18,39,27

In [5]:
df = pd.read_csv('data/wild.tsv', sep='\t')
print(df.shape)
df.head(15)

(5112, 9)

,geneName,wt t=0,wt t=10,wt t=20,wt t=30,wt t=45,wt t=60,wt t=90,wt t=120
0,MID2,0,-0.466758,-0.376290,-0.619178,-0.199123,-0.107018,-0.142740,-0.210389
1,RPS25B,0,-0.182692,-0.105678,-0.447844,-0.119024,-0.167358,-0.244887,-0.194087
2,NUP2,0,-0.238787,-0.140124,-0.804880,-0.153157,-0.164786,-0.358396,-0.182692
3,SGD1,0,0.543720,-0.178874,-0.718964,-0.052416,-0.209141,-0.178874,-0.115033
4,VRP1,0,0.011588,-0.132248,-0.120352,-0.166073,-0.257011,-0.442545,-0.546956
5,ATP14,0,-0.364012,-0.834307,-1.027154,-0.292782,-0.253384,-0.360645,-0.393965
6,YHC1,0,0.187707,-0.124328,-0.606916,-0.182692,-0.149259,-0.192825,-0.020058
7,ECM38,0,-0.723340,-0.523060,-0.387363,-0.361768,-0.668119,-0.737254,-0.716332
8,EXG1,0,-0.763836,-0.545968,-0.973060,-0.909197,-0.801573,-0.757877,-0.741575
9,MET17,0,-0.037031,0.222633,0.246395,0.172994,-0.064883,-0.046840,0.007232
10,ACO1,0,-1.614003,-1.731618,-1.599318,-0.495695,-0.323082,-0.756169,-0.633199
11,STT4,0,-0.339137,-0.550901,-0.646163,-0.302173,-0.470927,-0.695103,-0.635058
12,UBC12,0,-0.529071,-0.655352,-0.448901,-0.376290,-0.086784,-0.196607,-0.046840
13,CDA1,0,0.231075,0.161653,0.456009,0.384584,0.282790,0.181149,0.818579
14,CDA2,0,0.137648,0.060397,0.689660,0.137648,0.084670,0.080088,0.200913

In [6]:
df= pd.read_csv('data/gat1_d.tsv', sep='\t')
print(df.shape)
df.head(15)

(5062, 9)

,geneName,gat1-deletion t=0,gat1-deletion t=10,gat1-deletion t=20,gat1-deletion t=30,gat1-deletion t=45,gat1-deletion t=60,gat1-deletion t=90,gat1-deletion t=120
0,MID2,0.066427,0.013043,0.150401,0.224317,0.377070,0.237864,-0.035624,0.084670
1,RPS25B,-0.132248,-0.247320,-0.664483,-0.225275,-0.124328,-0.166073,-0.642471,-0.129613
2,NUP2,-0.060739,0.081614,0.452057,0.051399,0.194295,0.125006,-0.320773,-0.093560
3,SGD1,-0.075875,0.107803,0.140826,0.289827,0.541618,0.067939,-0.631337,-0.220330
4,VRP1,-0.339137,-0.380729,0.011588,-0.298658,-0.162210,0.002888,-0.386259,-0.543991
5,ATP14,0.078564,-0.264236,-0.632268,-0.341417,-0.008630,-0.180148,-0.829444,-0.553852
6,YHC1,0.023270,0.219270,-0.064883,-0.159629,-0.034216,-0.150560,-0.385155,-0.002883
7,ECM38,-0.429750,-0.901494,-0.950842,-0.896078,-0.695994,-0.292782,-0.562670,-0.666302
8,EXG1,0.351074,0.000000,0.057392,-0.094912,0.084670,0.222633,-0.446786,-0.037031
9,MET17,-0.151859,-0.308011,-0.098958,-0.007196,0.064917,0.020340,-0.129613,0.004335
10,ACO1,-0.431890,-1.622930,-0.547943,-0.506907,-0.449957,-0.662661,-1.417920,-1.244278
11,STT4,-0.279768,-0.426533,-0.491597,-0.594549,-0.147958,-0.261832,-0.588805,-0.391768
12,UBC12,-0.231432,-0.686164,-0.883621,-0.620117,-0.008630,-0.425459,-0.575312,-0.341417
13,CDA1,-0.097611,0.134477,0.336428,0.107803,0.220950,0.279284,0.430509,0.634867
14,CDA2,0.064917,0.029146,0.172994,0.110916,0.096962,0.036526,0.142417,0.078564

In [7]:
df = pd.read_csv('data/gcn4_d.tsv', sep='\t')
print(df.shape)
df.head(15)

(5112, 9)

,geneName,gcn4-deletion t=0,gcn4-deletion t=10,gcn4-deletion t=20,gcn4-deletion t=30,gcn4-deletion t=45,gcn4-deletion t=60,gcn4-deletion t=90,gcn4-deletion t=120
0,MID2,-0.146655,0.207561,0.367732,0.260152,0.312939,0.394032,0.302226,-0.147958
1,RPS25B,-0.326537,-0.298658,-0.214125,-0.074505,-0.423309,-0.534062,-0.302173,-0.473008
2,NUP2,-0.438293,0.021804,-0.228973,-0.301002,-0.284514,-0.123004,-0.128293,-0.599318
3,SGD1,-0.233888,0.698998,0.158429,-0.142740,-0.237564,-0.191563,-0.303342,-0.321928
4,VRP1,-0.195348,-0.202888,-0.186501,-0.273814,0.024737,-0.022900,-0.473008,-0.590722
5,ATP14,0.582080,-0.038436,0.107803,0.477944,0.650635,0.617056,0.067939,-0.313826
6,YHC1,-0.304511,0.039488,0.084670,0.089267,-0.098958,-0.225275,0.038006,-0.008630
7,ECM38,0.281036,-0.403813,-0.305679,-0.334568,-0.104337,0.084670,-0.325386,-0.804054
8,EXG1,0.253257,-0.141433,-0.090853,0.066427,-0.066261,0.086201,0.114035,-0.695994
9,MET17,-0.240009,-0.084064,-0.132248,-0.088142,-0.235114,-0.175045,-0.296311,0.318326
10,ACO1,-1.000721,-1.419539,-0.615416,-0.296311,0.090803,0.080088,-0.201634,-1.482332
11,STT4,-0.574344,-0.052416,-0.242450,-0.409255,-0.311503,-0.240009,-0.408168,-0.733788
12,UBC12,-0.328836,-0.635058,-0.459432,-0.507921,-0.283329,-0.224040,-0.361768,-0.195348
13,CDA1,-0.004322,0.200913,0.144010,0.067939,0.265345,0.190997,0.411195,0.454032
14,CDA2,-0.200379,0.066427,0.316528,-0.021480,-0.015783,-0.012926,-0.067639,0.388355

In [8]:
df = pd.read_csv('data/leu3_d.tsv', sep='\t')
print(df.shape)
df.head(15)

(5112, 9)

,geneName,leu3-deletion t=0,leu3-deletion t=10,leu3-deletion t=20,leu3-deletion t=30,leu3-deletion t=45,leu3-deletion t=60,leu3-deletion t=90,leu3-deletion t=120
0,MID2,-0.149259,-0.382944,0.182786,-0.007196,0.020340,-0.052416,0.074001,0.187707
1,RPS25B,-0.284514,-0.492622,-0.358396,-0.404903,-0.499782,-0.343692,-0.263034,-0.376290
2,NUP2,0.005782,-0.059355,0.239566,-0.062122,0.054392,-0.150560,0.128156,0.101598
3,SGD1,-0.439357,-0.246104,-0.147958,-0.112367,-0.241230,-0.242450,-0.197865,-0.331132
4,VRP1,-0.316146,0.078564,0.220950,-0.543991,0.018878,-0.489543,-0.266637,-0.097611
5,ATP14,-0.172488,-0.411426,-0.490570,-0.401630,-0.421156,-0.253384,-0.448901,-0.480265
6,YHC1,-0.001442,0.107803,-0.237564,0.090803,-0.176323,-0.005759,0.080088,0.186065
7,ECM38,0.526992,-0.140124,0.058894,-0.457332,-0.067639,-0.489543,-0.273814,-0.220330
8,EXG1,0.120294,-0.160920,0.018878,-0.292782,-0.028569,-0.136191,-0.146655,0.131313
9,MET17,-0.201634,-0.227741,-0.130931,-0.202888,-0.337996,-0.147958,-0.329985,-0.264236
10,ACO1,-0.319618,-0.941858,-0.190299,-0.371838,-0.157044,-0.432959,-0.562670,-0.852798
11,STT4,-0.368489,-0.282143,0.069452,-0.551885,-0.343692,-0.719841,-0.458382,-0.420078
12,UBC12,-0.440421,-0.644318,-0.500802,-0.244887,-0.337996,-0.399445,-0.455229,-0.528071
13,CDA1,-0.224040,-0.102994,-0.093560,-0.063503,-0.011496,0.104697,0.375197,0.411195
14,CDA2,0.014500,-0.220330,-0.046840,-0.086784,-0.102994,-0.066261,0.092340,-0.272620